version: '3'

services:
  project1:
    build:
      context: Project_1
      args:
        URL: "http://project2"
    ports:
      - 5000:80
    volumes:
      - './Project_1/src:/app'
    networks:
      - common
    depends_on:
      - project2
  project2:
    build: Project_2
    volumes:
      - './Project_2/src:/app'
    networks:
      - common
networks:
  common: